'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0"),
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()), MySettings)

#Region "Funcionalidad para autoguardar My.Settings"
#If _MyType = "WindowsForms" Then
        Private Shared addedHandler As Boolean

        Private Shared addedHandlerLockObject As New Object

        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
            If My.Application.SaveMySettingsOnExit Then
                My.Settings.Save()
            End If
        End Sub
#End If
#End Region

        Public Shared ReadOnly Property [Default]() As MySettings
            Get

#If _MyType = "WindowsForms" Then
                If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),
         Global.System.Configuration.DefaultSettingValueAttribute("Dsn=isis;server=agenda.medvital.com.py;uid=liberty;pwd={l1b3rty*};database=bdisis" &
            ";port=3337")>
        Public ReadOnly Property bdisisConnectionString() As String
            Get
                Return CType(Me("bdisisConnectionString"), String)
            End Get
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("""192.168.1.27""")>
        Public Property ip_servidor() As String
            Get
                Return CType(Me("ip_servidor"), String)
            End Get
            Set
                Me("ip_servidor") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("ftp://192.168.10.136:21")>
        Public Property ftp() As String
            Get
                Return CType(Me("ftp"), String)
            End Get
            Set
                Me("ftp") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("""192.168.1.27""")>
        Public Property ip_agenda() As String
            Get
                Return CType(Me("ip_agenda"), String)
            End Get
            Set
                Me("ip_agenda") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
       Global.System.Configuration.DefaultSettingValueAttribute("""C:\Program Files\MicroDicom\mDicom.exe""")>
        Public Property visorMicro() As String
            Get
                Return CType(Me("visorMicro"), String)
            End Get
            Set
                Me("visorMicro") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
      Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
      Global.System.Configuration.DefaultSettingValueAttribute("""C:\Program Files\RadiAntViewer64bit\RadiAntViewer.exe""")>
        Public Property visorRadiant() As String
            Get
                Return CType(Me("visorRadiant"), String)
            End Get
            Set
                Me("visorRadiant") = Value
            End Set
        End Property
    End Class
End Namespace

Namespace My

    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Module MySettingsProperty

        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>
        Friend ReadOnly Property Settings() As Global.osiris.My.MySettings
            Get
                Return Global.osiris.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace